import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/header/Header'
import { BsGithub, BsInstagram, BsLinkedin } from "react-icons/bs"
import Link from 'next/link'
import Card from '../components/card/Card'

export default function Home() {

  return (
    <>
      <Head>
        <title>ANDREA D&apos;ATTERO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Header />
        <section className="center" id='about'>
          <h1 className={styles.text}>Hello there, I am</h1>
          <p className={styles.name}>ANDREA D&apos;ATTERO</p>
          <p className={styles.subtitle}>I am a Software Engineer and I specialize in building, designing and engineering full stack applications across all devices. Currently I am developing applications for financial advisory at <a className="highlight" href="https://www.credit-suisse.com/ch/it.html" target="_blank" rel="noreferrer">Credit Suisse</a>.</p>
          <section className="row">
            <Link href="https://github.com/datteroandrea" target="_blank" rel="noreferrer"><BsGithub className="icon" size={30} color="#2C74B3" /></Link>
            <Link href="https://www.instagram.com/andrea.dattero/" target="_blank" rel="noreferrer"><BsInstagram className="icon" size={30} color="#2C74B3" /></Link>
            <Link href="https://www.linkedin.com/in/andrea-dattero-798990174" target="_blank" rel="noreferrer"><BsLinkedin className="icon" size={30} color="#2C74B3" /></Link>
          </section>
        </section>
        <section className="center" id='services'>
          <h1 className={styles.title}>Services</h1>
          <section className={styles.services}>
            <Card title="Small Application" price="Starts at 100.0 CHF" offer={["Static Website", "No API", "No Database", "No Additional Services"]} onClick={() => document.getElementById("contact")?.scrollIntoView()} />
            <Card title="Medium Application" price="Starts at 1000.0 CHF" offer={["Static and Dynamic Website", "Small API", "Small Database", "No Additional Services"]} onClick={() => document.getElementById("contact")?.scrollIntoView()} />
            <Card title="Large Application" price="Contact me!" offer={["Static and Dynamic Website", "Large API", "Large Database", "Search Engine Optimization, Backups, Live Chat, etc."]} onClick={() => document.getElementById("contact")?.scrollIntoView()} />
          </section>
        </section>
        {
          /*
          <section className="center" id='projects'>
            <h1 className={styles.title}>Projects</h1>
            <section className="row">
            </section>
          </section>
          */
        }
        <section className="center" id='contact'>
          <h1 className={styles.title}>Get In Touch</h1>
          <p style={{ maxWidth: "550px" }}>My inbox is always open for new adventures or business related inquiries.<br />Even though I am busy at the moment I will always try my best to reply to you as soon as possible!</p>
          <a className="contactButton" href="mailto:contact@datteroandrea.me" target="_blank" rel="noreferrer">Say Hello!</a>
        </section>
      </main>
    </>
  )
}
